kiwix/kiwix-apple

- iOS/Support/Info.plist
> add mirror.isoc.org.il and wiki.mirror.tn to ATS exception

- Shared/ZimMultiReader/ZimMultiReader.mm
I am not sure if it makes sense, but it makes the app build. 😄 
Changed in https://github.com/kiwix/kiwix-lib/commit/1e94665c0791b951a24fa0a831ff6ef341a85cc8/
> [ZMR] - Update usage of Searcher::add_reader to new signature

- Kiwix.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- macOS/Storyboard/Main.storyboard
> macOS app missing button icon

- iOS/Controller/ContentViewController.swift
- iOS/Controller/RootSplitViewController.swift
Per request from @kelson42 in #225
> Make the side menu not visible when app launch in landscape

- iOS/Controller/Search/SearchResultsListController.swift
> add dark mode specific logic for search result snippet

- CHANGELOG.md
- iOS/Controller/Web/WebKitWebController.swift
> Fixing font adjustment issue on iPhones

- iOS/Main.storyboard
> Fix: prevent the preview label from becoming too tall

- Kiwix.xcodeproj/project.pbxproj
- iOS/AppDelegate.swift
- iOS/Controller/ContentViewController.swift
- iOS/Controller/Library/LibraryZimFileDetailController.swift
- iOS/Controller/RootController.swift
- iOS/Controller/Setting/SettingFontSizeController.swift
- iOS/Controller/SideBar/OutlineController.swift
- iOS/SceneDelegate.swift
> iOS12 init issue

- CHANGELOG.md
- iOS/Controller/RootController.swift
- iOS/Controller/Search/SearchResultsController.swift
> more iOS12 specific fixes

- CHANGELOG.md
- Model/LibraryOperations/LibraryOperationBase.swift
> fix: favicon would disappear for existing zim files after library manual refresh

- iOS/Controller/Library/LibraryLanguageController.swift
> fix: library language sort alphabetically

- iOS/Controller/RootController.swift
> hack to prevent unnecessary UI adjustment in the background

- CHANGELOG.md
- Model/Services/BookmarkService.swift
- Model/Utilities/Log.swift
- Model/Utilities/WebKitHandler.swift
- Model/ZimMultiReader/ZimMultiReader.swift
- iOS/Controller/ContentController.swift
- iOS/Controller/SideBar/BookmarkController.swift
- iOS/Controller/Web/WebKitWebController.swift
> Resource Unavailable alert

- .gitignore
- CHANGELOG.md
- Kiwix.xcodeproj/project.pbxproj
- Kiwix.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Model/Entities/ZimFileMetaData.mm
- Model/Operations/OPDSRefreshOperation/OPDSStreamParser.mm
- Model/Operations/SearchOperation/SearchOperation.mm
- Model/ZimMultiReader/ZimMultiReader.mm
- updated version of libkiwix and dependencies to resolve an issue where the app couldn't open some of the latest zim files
- updated version of realm to 5.2
> 1.13.2 -- Update libkiwix

- Kiwix.xcodeproj/project.pbxproj
- Kiwix.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Model/Entities/ZimFileMetaData.h
- Model/Entities/ZimFileMetaData.mm
- Model/Operations/LibraryOperationBase.swift
- Model/Operations/OPDSRefreshOperation/OPDSRefreshOperation.swift
- Model/Realm/RealmConfig.swift
- Model/Realm/ZimFile.swift
- Model/Utilities/FeatureFlags.swift
- iOS/Controller/RootController.swift
- iOS/SceneDelegate.swift
Disable swipe gesture to reveal the sidebar on iPad -- #324
> iOS 1.13.7

- Model/Entities/ZimFileMetaData.h
- Model/Entities/ZimFileMetaData.mm
- Model/Operations/LibraryOperationBase.swift
- Model/Operations/OPDSRefreshOperation/OPDSRefreshOperation.swift
Implementation of #363.
At the same time, added some other minor improvements / dead code removal
> OPDS: hide zim files that require service worker

- CHANGELOG.md
- Model/Operations/LibraryScanOperation.swift
- Model/Operations/OPDSRefreshOperation/OPDSRefreshOperation.swift
- Model/Realm/RealmConfig.swift
- Model/Realm/ZimFile.swift
- Model/Services/Queries.swift
- iOS/SwiftUI/Library/LibraryCategoryView.swift
- iOS/SwiftUI/Library/LibraryPrimaryView.swift
- iOS/SwiftUI/SearchResultsView.swift
- macOS/Controller/NavigationController.swift
> Revert "Schema change"

- Kiwix.xcodeproj/project.pbxproj
- Model/Operations/SearchOperation/SearchOperation.swift
- iOS/SwiftUI/Library/LibraryCategoryView.swift
- iOS/SwiftUI/Library/LibrarySearchResultView.swift
- iOS/SwiftUI/SearchResultsView.swift
> Search result view refactor & fixes

- Kiwix.xcodeproj/project.pbxproj
- Model/Services/ZimFileService/ZimFileService.mm
- iOS/Controller/RootViewController.swift
`kiwix::NoEntry` was raised when retrieving random articles, wrapping the function call with try except. Then adding an alert to show user something went wrong
> Try catch random page function

- README.md
At least I got it working on macOS (M1)
> Updating build steps for the libkiwix

- CHANGELOG.md
- Model/Entities/Entities.swift
- Model/Utilities/WebKitHandler.swift
- Model/ZimFileService/ZimFileService.h
- Model/ZimFileService/ZimFileService.mm
- Model/ZimFileService/ZimFileService.swift
Implementing HTTP 206 Partial Content based on spec from https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests
> Implementing HTTP 206

- CHANGELOG.md
- Kiwix.xcodeproj/project.pbxproj
- Kiwix.xcodeproj/xcshareddata/xcschemes/Kiwix.xcscheme
- Kiwix.xcodeproj/xcshareddata/xcschemes/WikiMed.xcscheme
- Model/Entities/Entities.swift
- Support/Info.plist
- SwiftUI/App.swift
- SwiftUI/Model/DataModel.xcdatamodeld/DataModel.xcdatamodel/contents
- SwiftUI/Model/Database.swift
- SwiftUI/Model/Enum.swift
- SwiftUI/RootViewV2.swift
- iOS/CompactViewController.swift
- iOS/SidebarViewController.swift
- iOS/SplitViewController.swift
Setting up tab management for iOS and iPadOS
> iOS / iPadOS tab management setup

- README.md
Fixes #508
* Few sections reorganisation
* Clarification about OS support
* Clarification about CPU architecture support
The `README.md` is on a few points a bit ahead on the reality, but we work to fix the gap next week.
> Multiple clarifications around system support

- .github/workflows/cd.yml
At least until #545 is figured out
> only upload to Apple upon releases

- SwiftUI/Model/Database.swift
Fixes #557
Both iOS and macOS apps were missing the notification values, as the wrong one was used.
It turned out that the older value (coming from Obj-c under interop objc++ mode) should be used.
> Fix download notification name

- SwiftUI/Model/Formatter.swift
- ViewModel/BrowserViewModel.swift
- Views/Buttons/BookmarkButton.swift
Fixes: #555, cherry pick from https://github.com/kiwix/apple/pull/578, to be applied on the custom app support lane.
> Fix bookmarks

- Model/Brand.swift
- Views/Settings/About.swift
> #553 custom about text and link

- Brewfile
- project.yml
> Fix first time build of the project

- Support/fr.lproj/Localizable.strings
> Localisation updates from https://translatewiki.net.

- Support/Info.plist
- Support/kiwix.xcconfig
- project.yml
> Remove xcconfig file, inline App Store ID

- .github/retry-if-retcode.py
- .github/workflows/cd.yml
> Revert CD archive to use python re-try

- Model/Entities/Entities.swift
- Model/Entities/ZimFileMetaData/ZimFileMetaData.h
- Model/Entities/ZimFileMetaData/ZimFileMetaData.mm
- SwiftUI/Model/LibraryOperations.swift
- Views/Library/ZimFileDetail.swift
> Replace deprecated function: book->getLanguage() with book->getCommaSeparatedLanguages()

- .github/actions/xcbuild/action.yml
- .github/workflows/cd.yml
- .github/workflows/ci.yml
Simplifying the CI / CD steps, to make them more readable. Part 2
> 545: simplify current CI / CD steps (part 2)

- .github/actions/xcbuild/action.yml
- .github/workflows/cd.yml
- .github/workflows/ci.yml
- project.yml
Trying to simplify the CD steps to be more readable before updating it to support the requests in the ticket.
> Simplify CD steps

- .github/workflows/cd.yml
Fix the nightly upload folder destination.
> Fix nighly folder

- Tests/LibraryRefreshViewModelTest.swift
- Tests/OPDSParserTests.swift
- ViewModel/LibraryViewModel.swift
- Views/Settings/LanguageSelector.swift
> Fix default language for library filtering

- README.md
> Add Deployment Readme

- project.yml
> Filter out igl lang code

- .github/workflows/ci.yml
- Model/Entities/ZimFileMetaData/ZimFileMetaData.mm
- project.yml
> CI make sure we run Unit Tests step

- Support/en.lproj/Localizable.strings
> Uppercase ZIM

- README.md
Following https://github.com/kiwix/apple/issues/675#issuecomment-1974699348
> Instructions to upload app container

- CHANGELOG.md
- Tests/NavigationViewModelTest.swift
- ViewModel/NavigationViewModel.swift
> Fix tab selection post deletion

- project.yml
> 710 custom apps should only request necessary permissions

- App/App_macOS.swift
> Close the app, when the last window is closed

- App/App_macOS.swift
- Model/Brand.swift
- Support/de.lproj/Localizable.strings
- Support/en.lproj/Localizable.strings
- Support/qqq.lproj/Localizable.strings
- SwiftUI/Patches.swift
- Views/Settings/Settings.swift
> Add support link item in side bar

- App/App_macOS.swift
- App/CompactViewController.swift
- App/SplitViewController.swift
- Views/Library/Library.swift
- Views/Library/ZimFileDetail.swift
- Views/Library/ZimFilesOpened.swift
- Views/Welcome.swift
> Dismiss modals on iOS when opening main page

- App/App_macOS.swift
- App/CompactViewController.swift
- App/SplitViewController.swift
- Model/Brand.swift
- Support/de.lproj/Localizable.strings
- Support/en.lproj/Localizable.strings
- Support/qqq.lproj/Localizable.strings
- ViewModel/BrowserViewModel.swift
- Views/Library/Library.swift
- Views/Library/ZimFileDetail.swift
- Views/Library/ZimFilesOpened.swift
- Views/Settings/Settings.swift
- Views/Welcome.swift
> Detect cmd+click event to open link on new tab

- App/App_macOS.swift
- Views/ViewModifiers/FileImport.swift
> 699 double clicking a zim opens multiple windows

- README.md
- Views/Settings/About.swift
I have done the repository renaming, here a few changes in the code base to reflect that change.
Fixes #709
> Rename code repository to kiwix/kiwix-apple

- README.md
> Update README on white space settings in Xcode

- App/App_macOS.swift
- SwiftUI/Model/LibraryOperations.swift
- ViewModel/NavigationViewModel.swift
> Fix unlinked ZIM file tab data

- App/App_macOS.swift
- App/SplitViewController.swift
- Views/Library/Library.swift
- Views/Library/ZimFileDetail.swift
- Views/Library/ZimFilesCategories.swift
- Views/Library/ZimFilesDownloads.swift
- Views/Library/ZimFilesNew.swift
Fixes #714 
There were some additional cases that needed the same treatment as before.
> 714 dimiss fixes part2

- Support/en.lproj/Localizable.strings
- Support/qqq.lproj/Localizable.strings
- SwiftUI/Patches.swift
- Views/BrowserTab.swift
- Views/Buttons/PrintButton.swift
- Views/Buttons/ShareButton.swift
- project.yml
> 282 print an article on macos

- Model/Utilities/Bundle+Extension.swift
- ViewModel/BrowserViewModel.swift
Related to: #215 
This should work only for DEBUG builds and probably for TestFlight builds as well.
> Make webView inspectable / debuggable

- Views/ViewModifiers/SaveContentHandler.swift
> Fix localization

- App/App_macOS.swift
- Model/Brand.swift
- Views/Settings/Settings.swift
> Remove support external link

- Views/BuildingBlocks/WebView.swift
Fixes: #741 
After several hours of digging, I've finally found it.
> Fix macOS video full screen mode

- Views/BuildingBlocks/WebView.swift
Fixes: #741 
Limiting the change to macOS only.
> Full screen fix to macOS v2 (limit to macOS only)

- Views/BuildingBlocks/WebView.swift
> Fix macOS webView full-screen mode

- Model/Entities/Entities.swift
- Model/ZimFileService/ZimFileService.mm
- Model/ZimFileService/ZimFileService.swift
- ViewModel/BrowserViewModel.swift
> Fix PDF tab title and opening _blank in new tab on iOS

- project.yml
> Min version to mac 13, iOS 16

- App/CompactViewController.swift
- ViewModel/BrowserViewModel.swift
- Views/BrowserTab.swift
> Fix video stop, when tab is closed

- README.md
> Clarification around video known bugs

- README.md
> Add web inspecting docs

- Brewfile
> Update to libkiwix 13.1.0-4

- CHANGELOG.md
Update the Change logs for release 3.4.0
> Update changelog for release 3.4.0

- Views/BuildingBlocks/WebView.swift
> Remove default zoomScale, that causes wrong content adjustment

- Support/injection.js
Fixes: #772 
Naive was the implementation thinking that jQuery will always be available...
> Fix resume video without jQuery

- App/App_macOS.swift
- Model/Utilities/WindowTracker.swift
- SwiftUI/Patches.swift
- Views/ViewModifiers/FileImport.swift
> Fix multi window issue when opening an external file

- .pre-commit-config.yaml
> Add SPM resolve to pre-commit

- Views/Buttons/OutlineButton.swift
- project.yml
> Remove BackPorts dependency

- App/CompactViewController.swift
- Views/Buttons/NavigationButtons.swift
> Fix Accessibility of icons when large text is set

- Views/BuildingBlocks/WebView.swift
Fixes: #889 
After many attempts, this one is fixing this specific issue on macOS, I left some comments in the code to make it more clear.
> Fix macOS video fullscreen sizing when paused

- App/App_macOS.swift
> Fix window will close notification, making sure it's from our window

- Model/Entities/Entities.swift
- Model/LanguageCollector.swift
- Tests/LanguageCollectorTest.swift
- Views/Settings/LanguageSelector.swift
Fixes: #905 
Based on the PR from: @HiroyasuNishiyama here: 
https://github.com/kiwix/kiwix-apple/pull/903
With some changes:
- make the language collecting / counting a separate unit
- make sure it's tested for edge cases
- use less loops to do the same amount of work
> Fix multi-language ZIM listing and count, add unit tests

- Views/Library/ZimFilesNew.swift
> Update search for New ZIM files, to search in descriptions as well

- Views/Library/ZimFilesNew.swift
> Increase the lifespan of NEW categories to be 3 months

- Model/DownloadService.swift
- Support/en.lproj/Localizable.strings
- Support/qqq.lproj/Localizable.strings
- SwiftUI/Model/Enum.swift
- Views/ViewModifiers/AlertHandler.swift
Fixes: #900 
It is fixing actually only part of the ticket, which is how we handle the download errors:
https://github.com/user-attachments/assets/89dad530-7053-478e-85d1-889f7183f848
> Handle download status code errors

- Support/injection.js
- ViewModel/BrowserViewModel.swift
> Disable video context menu on macOS

- Support/en.lproj/Localizable.strings
- Support/qqq.lproj/Localizable.strings
> Update Bookmarks sheet button accesibility

- Views/BuildingBlocks/FlavorTag.swift
> Fix localized key

- Views/BuildingBlocks/ZimFileRow.swift
> Add space in article count label

- CHANGELOG.md
CHANGELOG entries for release 3.5.0
See #901
> Update CHANGELOG for 3.5.0

- project.yml
Update project version to 3.5.1, and bump up the build version as per release notes.
Related to #951
> Update project versions

- App/App_macOS.swift
- App/CompactViewController.swift
- App/SidebarViewController.swift
- CHANGELOG.md
- Support/injection.js
- ViewModel/BrowserViewModel.swift
- Views/BrowserTab.swift
> 948 Fix leaving or entering pip pause the video

- CHANGELOG.md
- project.yml
Post release duties, version to 3.6.0, build number to 173
> Post release duties, version to 3.6.0, build number to 173

- Views/BuildingBlocks/WebView.swift
Fixes: #994
Extending the `immerse reading` that was done for iPhone for iPad as well.
https://github.com/user-attachments/assets/6559c470-07a8-438a-aa72-e7b36472cfe5
> 994 - Extend 'immerse reading' for iPad as well

- ViewModel/BrowserViewModel.swift
> Use webView loading while restoring a tab

- App/App_macOS.swift
- ViewModel/BrowserViewModel.swift
- ViewModel/NavigationViewModel.swift
> 962 macos windows for zim opening

- .github/workflows/cd.yml
- .github/workflows/ci.yml
> Remove hack around apple-pay capability for macOS

- CHANGELOG.md
> Update changelog for 3.7.0

- .github/workflows/cd.yml
Trying to fix the CD process for macOS, applying the same solution as in: 
https://github.com/kiwix/kiwix-apple/pull/1046/files
> Fix CD process for macOS

- .github/actions/xcbuild/action.yml
- project.yml
> Update CI to Xcode 15.2

- .github/actions/xcbuild/action.yml
- .github/workflows/cd.yml
Fixes: #1065 
Removing some unused arguments from CI / CD process, to make things cleaner.
> Remove unused parts from CI / CD

- Widgets/Info.plist
We need one more thing to be fixed for TestFlight builds, the widget extension needs a name to be defined.
> Fix bundle extension name

- README.md
> Add Apple Store link to README

- .github/actions/xcbuild/action.yml
As part of [this dependency update](https://github.com/kiwix/kiwix-apple/issues/1104), switching our CI/CD to use Xcode 16.2.0
> Update to Xcode 16.2

- .github/actions/xcbuild/action.yml
> Update to Xcode 15.4 on CI

- App/App_iOS.swift
- CHANGELOG.md
- project.yml
Removing live activities from release 3.8.0
> Remove live activities from release 3.8.0

- project.yml
> Milestone 3.9.0 preps

- App/App_macOS.swift
- Model/Payment.swift
Fixes: #1115
Solves the error message:
```
Publishing changes from within view updates is not allowed, this will cause undefined behavior.
```
Also improves the side menu performance. After careful measuring in Instruments, it turned out the checking for Apple Pay status is quite expensive to be done synchronously on the main thread. This check was causing the side menu to be slow.
> 1104 side menu optimalization

- App/SplitViewController.swift
Fixes: #1138
When backgrounding and foregrounding the app, the trait collection also changes, but we should not react to it in background mode as it will change the selection of the side menu.
> Fix remembering side menu selection on iPad after background / foreground

- App/App_iOS.swift
> Fix background mode scheduler for live activities

- App/SidebarViewController.swift
> Fix menu item configurations

- Model/Brand.swift
- Views/BuildingBlocks/WebView.swift
Fixes: #1152 
Adding an optional way to turn off immersive reading.
> Add feature flag to turn off immersive reading (custom apps)

- Views/ViewModifiers/CellBackground.swift
> Revert selected cell color for iOS

- App/CompactViewController.swift
- Model/Brand.swift
- Views/BrowserTab.swift
- Views/BuildingBlocks/ArticleActions.swift
- Views/Buttons/ArticleShortcutButtons.swift
Implements the common code part of: https://github.com/kiwix/kiwix-apple-custom/issues/98
> Make random button optional for custom apps

- App/CompactViewController.swift
- Model/Brand.swift
- Views/BrowserTab.swift
> Optionally disable TOC Button, Share button, Find in Page

- Support/Info.plist
Fixes: https://github.com/kiwix/kiwix-apple-custom/issues/102
> Remove unused background processing mode

- Model/OPDSParser/OPDSParser.h
- Model/OPDSParser/OPDSParser.mm
- Model/OPDSParser/OPDSParser.swift
- Model/Utilities/String+Extension.swift
- Model/Utilities/URL.swift
- Tests/LibraryRefreshViewModelTest.swift
- Tests/OPDSParserTests.swift
- Tests/URLContentPathTests.swift
- ViewModel/LibraryViewModel.swift
- Views/BuildingBlocks/Favicon.swift
> Library endpoint changes

- App/SidebarViewController.swift
Fixes: #1209 
Still trying to figure out the test part of this, that will be in a new PR.
> Fix sidebar selection on app restart

- App/App_iOS.swift
- App/App_macOS.swift
- Support/en.lproj/Localizable.strings
- Support/qqq.lproj/Localizable.strings
- SwiftUI/Model/UserColorScheme.swift
- Views/Settings/Settings.swift
> 516 Dark/Light Theme custom settings

- SwiftUI/Model/UserColorScheme.swift
> Fix theme selection by system for macOS

- App/CompactViewController.swift
- SwiftUI/Patches.swift
- Views/Buttons/ShareButton.swift
- Views/Hotspot/HotspotAddress.swift
- Views/Hotspot/HotspotZimFilesSelection.swift
Adding share functionality for Hotspot server URL.
Related to: #170
> 170 hotspot share

- Tests/DatabaseTests.swift
- Tests/LibraryRefreshViewModelTest.swift
- Tests/TestDatabase.swift
- ViewModel/LibraryViewModel.swift
- ViewModel/ZimSelectionViewModels.swift
- Views/BuildingBlocks/ZimFileCell.swift
Further fixes for macOS CI Tests.
> Fix macOS CI tests

- Support/en.lproj/Localizable.strings
- Support/qqq.lproj/Localizable.strings
- Views/Hotspot/HotspotObservable.swift
> Rename to: Start/Stop Hotspot

- CHANGELOG.md
- project.yml
Related to 3.10.0 release: #1229
> Update version to 3.10.0, edit changelog

- Model/Hotspot/Hotspot.swift
Fixes #1288 
Since we are stopping and restarting the Hotspot when coming back from App being in background, we should not do state updates.
> Fix blinking on appDidBecomeActive

- Model/Hotspot/Hotspot.swift
> Set default Hotspot port to 80

- .github/actions/xcbuild/action.yml
- .github/workflows/cd.yml
- .github/workflows/ci.yml
- Views/BrowserTab.swift
Update to macOS 15 github runner with Xcode 26
> Update to macOS-15 runner and Xcode 26
