kiwix/kiwix-apple

iOS/Controller/Tab/WebKitWebController.swift
As there is no native support for webm in Webkit, we use a JS implementation
of the codec, called using video.js.
the mechanism is use fails to be detected by webkit as a "user-initiated play" resulting
in webm videos to be paused immediately on play.
To overcome this, we allow all media files to be played without user action.
> previous youtube ZIM files had autoplay enabled.
=> allow webm video files to play using videojs-ogvjs

CHANGELOG.md, iOS/Controller/RootController.swift
Fixed an issue where it could lead to app launch crashes on iOS 12 (iPhone or iPad horizontally compact interface). See #322
=> fix: iOS 12 launching issue

iOS/Controller/Library/LibraryCategoryController.swift, iOS/Controller/Library/LibraryMasterController.swift
There has been ac increasing number of crashes like these. No idea of what the root cause is, since none of mine code has changed on these areas for nearly a year. It could very possible that this is on realm or UIKit side. Anyway, I changed the deletion + insertion to just reload section and find the visual result identical or similar. 
This is a more permanent solution for #329
=> safer library list update

Kiwix.xcodeproj/project.pbxproj, Model/Operations/SearchOperation/SearchOperation.swift, iOS/SwiftUI/SearchResultsView.swift
- early exit when search text is empty
- url escaping when search text has stuff like spaces
=> Fix two search related issues

CHANGELOG.md, Model/DownloadService.swift, SwiftUI/App.swift
Fixing an issue where task is not labeled as failed when user force quit the app.
=> Download task on force quit

SwiftUI/Patches.swift, ViewModel/BrowserViewModel.swift, Views/ViewModifiers/ExternalLinkHandler.swift
There has been an issue on the external URL alert that was left over from my last round of refactoring in the context of multi tabs on iOS / iPadOS. When there are multiple tabs, the alert would show up on all tabs, because it is openURL / notification based.
Instead, I am using a `externalLink` variable in the view model (which is unique to each tab) to store if there is any external link that needs to be handled
=> Fix external link alert macOS

App/App_iOS.swift, App/App_macOS.swift, App/CompactViewController.swift, Kiwix.xcodeproj/project.pbxproj, Model/Brand.swift, Model/Utilities/String+Extension.swift, Support/DefaultLanguages.swift, Support/de.lproj/Localizable.strings, Support/en.lproj/Localizable.strings, SwiftUI/Model/DefaultKeys.swift, Views/Bookmarks.swift, Views/BrowserTab.swift, Views/BuildingBlocks/LoadingView.swift
Fixes #594 
We want to enforce the localization of the apps.
There are a couple of limitations in this:
- Apple is choosing which language should be selected by default on it's own.
- It is possible to override the UserDefaults "AppleLanguages", but swift UI cannot do this early enough (main function is provided by Apple and we don't know how to re-implement it in a safe way to override), 
- The result is that t**he full enforcement of the language only works on the second launch of the app** (not fresh install)
- On fresh install we can override the bundle we use to search for localised strings, which works OK, except the search bars' cancel button, which is currently using the system provided button.
Since this is a first launch only issue, and not really visible without using the …
=> Enforce localization for custom apps

Model/DownloadService.swift, Support/en.lproj/Localizable.strings, Views/ViewModifiers/FileImport.swift
Fixing issue #585 by replacing "lego" translations with positional arguments and placeholders.
=> 585: Replace 'lego' translations with placeholders and arguments

.github/actions/xcbuild/action.yml, .github/workflows/cd.yml, .github/workflows/ci.yml, README.md
Fixing #609 
- Update the CI and CD workflows which were relying on a specific libkiwix version.
- Update the README to reflect that the Brewfile is setting the version of libkiwix to be used.
=> post XcodeGen: Remove libkiwix version from gitactions, update readme

Model/Brand.swift, Views/Settings/About.swift
Part of fixing: https://github.com/kiwix/kiwix-apple-custom/issues/10
We want to replace hard coded https://, to be able to use a full url in our custom info.jsons.
=> Use full urls for websites

.github/actions/xcbuild/action.yml
Adding an additional flag to the build workflow, if the dependencies should be downloaded as part of this workflow or not.
Will be handy for custom apps, for which we resolve the dependencies earlier.
=> Download dependencies on build step according to parameter

SwiftUI/Model/SearchOperation/SearchOperation.mm
Fixes #635
Fixes #631
The wikimed custom app was crashing if the user did any search.
Use a similar implementation as on Android, to avoid errors to be thrown when the search result has an empty title.
Filter out any empty titles, as they won't be useful for the end user (it creates blank lines in search results).
=> Fix search crashing

.github/workflows/ci.yml
We want to update our CI / CD process, here: https://github.com/kiwix/apple/pull/641
In order to safely do this, we need to run the changed files on GithubAction.
The CD process can be triggered manually on a specified branch, however the CI process not.
The pull request itself is triggering the main branch's CI process, but that's not what we want to check in this case.
For this reasons, we need to enable the manual trigger for CI as well.
We can remove it, once we finish working on these updates, if needed.
=> Enable manual workflow for CI

.github/workflows/cd.yml
Fixes: #545 
We want to keep our nightly CD, uploading to FTP (as before),
add weekly (if there's a code change) should upload to App Store,
and a post App Store release flow, uploading only macOS to FTP.
=> CD: add nightly, weekly, "testFlight" tag and post App Store release flows

App/App_macOS.swift, Model/CategoriesToLanguage.swift, Model/Entities/Entities.swift, SwiftUI/Model/DefaultKeys.swift, SwiftUI/Model/Enum.swift, ViewModel/LibraryViewModel.swift, Views/Library/Library.swift, Views/Library/ZimFilesCategories.swift, Views/Settings/LanguageSelector.swift, Views/Settings/Settings.swift
Fixes: #656 
Also fixes: the language count in settings, and a translations of drop downs in settings.
With this we filter down the categories to non empty ones, depending on the content language settings. Eg: setting it to German only (we won't have TED, which is currently only available in English):
=> Filter categories by content languages

Model/Utilities/InSync.swift, Model/Utilities/WebKitHandler.swift, Support/Kiwix-Bridging-Header.h, ViewModel/BrowserViewModel.swift, Views/BuildingBlocks/WebView.swift, Views/Buttons/ArticleShortcutButtons.swift
Fixes #676 
The requests sent to Webkit are handled in a delegate called `WKURLSchemeHandler`. This is making sure that we intercept the request if it starts with the "kiwix" scheme.
Most of the time this was working, although as we start to navigate (or load a random page) at different rates, things can go wrong.
As of Apple's documentation, once a URL scheme task is finished / or errored out, we should no longer use it.
Also as of Apple all of the functions on this scheme task should be called from the main thread.
There were random cases where, the requests and tasks were overlapping, and we ended up sending data, when the task was already finished.
- Add a keyboard shortcut (cmd+option+R) to random page button, this way it can be pressed and hold, which will keep loading random pages …
=> Fix webkit sync, and add shortcut cmd+option+R for random page

Model/Entities/Entities.swift, Model/ZimFileService/ZimFileService.h, Model/ZimFileService/ZimFileService.mm, Model/ZimFileService/ZimFileService.swift, Support/Kiwix-Bridging-Header.h, SwiftUI/Model/LibraryOperations.swift, Tests/LibraryRefreshViewModelTest.swift, ViewModel/LibraryViewModel.swift, Views/Library/ZimFilesOpened.swift, Views/SearchResults.swift
Initial clean up PR, that removes unused functions, clarifies the misleading naming of file URL Bookmark, which has nothing to do with the Bookmarks really.
No change of functionality, just more clarity in code.
=> 601 bookmarks intial cleanup

SwiftUI/Model/DefaultKeys.swift, ViewModel/LibraryViewModel.swift, Views/Library/ZimFilesNew.swift, Views/Settings/LanguageSelector.swift, Views/Settings/Settings.swift, Views/Welcome.swift
Fixes #680
The initial state of the applications is that we do not have a list of languages.
We need to indicate it to the user in a reasonable way.
On macOS we also need to update the list of languages if the initial refresh starts from the settings (the same tab, where the list of languages are displayed).
On iPhones the list of languages is under a different section in the settings menu, but that navigation link should also be disabled, when there are no languages to select from.
Also while we are refreshing the language selection should be disabled for the user.
After the changes:
Similarly on iOS:
=> Fix language selection initial state UI problems

Model/DownloadService.swift, SwiftUI/Model/Database.swift
Fixes #634 
Tested on the attached "broken" Library/container.
The very specifics how downloads and progress are working:
- download starts via http, and we get progress updates, eg: 500 bytes loaded out of 2MB
- these progresses are marked in the SQLite Database under "DownloadTasks"
- the DB is updated from the background context, this allows CoreData syncing to the "view context", and swift ui views are automagically updated
- for this syncing to happen it looks up the list of transactions from a specific time stamp, called token, which is stored in UserDefaults
The token is invalid in the "broken" container, meaning there are no transactions to be found after this date.
This can happen for various reasons, either some transactions were corrupted, or old transactions were deleted (as …
=> 634 ZIM download progress fix

Views/Settings/LanguageSelector.swift
It is fixing a very edge case of invalid default language selection, I could reproduce from the container uploaded by @kelson42 .
So far I cannot re-create the same crash, but lets try with this fix first merged.
So the issue here is that if there are earlier downloaded files, with 2 letter language codes, they will "count" as valid language codes (since downloaded entries are not cleaned-up in our language migration).
This makes sure we only take "valid" language codes from ZIM files that are not yet downloaded, since we will filter not yet downloaded entries anyway with those language codes.
=> Fix default language when there's downloaded content already

App/CompactViewController.swift, Views/Buttons/TabsManagerButton.swift
Fixes #532 
Fixes #474 
Re-arranged the buttons, so no long press is needed to access them:
=> 532 remove long press and re-arrange buttons

Views/Buttons/BookmarkButton.swift
Fixes #532 additional feature change:
Adding the option to add and remove bookmarks without long-press gesture as well, by adding the bookmark icon to the opened sheet top right menu item.
It can have 3 states: 
- disabled if no url is loaded
- enabled, but off - when the url is not bookmarked
- enabled and on - when the url is bookmarked already
=> 532 bookmark no long press

Model/Entities/Entities.swift, Model/Utilities/WebKitHandler.swift
Fixes #698 
It is displayed as expected:
=> Add UTF-8 encoding to HTTP headers for text/plain

Views/ViewModifiers/ExternalLinkHandler.swift
Fixes #701 
The issue is that since we were only listening to externalURL **changes**, when the same link is clicked again,
it did not "changed".
The simplest solution is to `nil' out the `externalURL`, once the alert is closed, either by cancel or by accepting to open the URL.
=> Fix same link opened alerts

SwiftUI/Model/SearchOperation/SearchOperation.mm
Preparing for handling standard exception raised as part of #622 .
Fixes #622
=> 622 corrupted zim leads to crash

Support/Info.plist
Relates to: #215 
This PR is a summary of my findings so far, and a minor fix for iOS, by adding the background processing and audio capabilities to the apps.
So far by using the test TED ZIM file for videos, I have found the following:
**iOS:** 
There are only small issues really: 
- when you first load a page with the video, it will start the audio but the screen will be black. If you close the video (fullscreen) and re-open the same video, everything is fine. Also if you toggle to Picture in Picture that fixes it as well.
- I couldn't make it stream to Apple TV via Airplay for some reason
Other than these 2 issues, it works perfectly, you can scrub, mute, change subtitles, use picture and picture, which properly closes if you leave the page, and even resumes when you go back. The …
=> Seek videos

.github/workflows/cd.yml
=> Target FTP forlder for release

Model/Utilities/WebKitHandler.swift
Related to: https://github.com/kiwix/kiwix-apple/issues/744
Version 2, without Range Requests changes.
Make UX more smooth, when loading html content, especially large item, such as videos.
The former solution was loading the content (including video content) on the main thread of the application, as part of a synchronised queue. In practice it meant, that the UI became unresponsive while the video was loading.
To solve this, we can read the content on a utility thread, and once completed there, we can send the results back to WebKit.
Before: it was possible to block the UI thread with larger videos (that were not pre-loaded yet), even the "rainbow spinning wheel" was visible on macOS.
After: the UI remains responsive (the user can eg. scroll in the meantime), no more system spinning …
=> Move HTML content loading off the UI thread (version2)

ViewModel/BrowserViewModel.swift
=> Add support for target=blank links

Model/Entities/Entities.swift, Model/Utilities/ByteRanges.swift, Model/Utilities/DataStream.swift, Model/Utilities/WebKitHandler.swift, Model/ZimFileService/ZimContentProvider.swift, Model/ZimFileService/ZimFileService.h, Model/ZimFileService/ZimFileService.mm, Model/ZimFileService/ZimFileService.swift, Tests/ByteRangesTests.swift, Tests/DataStreamTests.swift
Fixes: #773 
Reading the content in "chunks".
Both direct and indirect / ZIM streaming data solution is added.
Currently the ZIM streaming is not in use, until the offset issue is resolved on the libZIM side (see https://github.com/openzim/libzim/issues/886).
There are still issues with syncing the urlScheme closing, and maybe it's worth to add a Task cancelation, when the user leaves the currently loading page.
=> 773 streaming uncompressed data

Model/Utilities/WebKitHandler.swift, Model/ZimFileService/ZimFileService.mm
=> 784 stream data in chunks for compressed data via libzim

App/App_iOS.swift, App/App_macOS.swift, Model/Utilities/URL.swift, ViewModel/BrowserViewModel.swift
=> Change "mailto:" urls to be external

Model/Utilities/String+Extension.swift, Model/Utilities/URL.swift, Model/ZimFileService/ZimFileService.swift, Tests/URLContentPathTests.swift, ViewModel/BrowserViewModel.swift
Fixes: #793 
Made sure that we suport urls to contentPath ending with "/",
we drop if there's any "#" symbol with additional arguments there (which was also failing).
Fixed the issue with the error pop-up, now only a failing "main" document should trigger the pop-up.
Tested with "Mes quartiers chinois":
=> 793 supporting entries ending in "/"

Support/injection.js, ViewModel/BrowserViewModel.swift, Views/BrowserTab.swift
Fixes: #772 
Note: So far I only found this "hacky" javascript solution to fix this issue.
The traditional "low memory" warning triggers are not called in this case, therefore this black screen side effect is not due to that.
By playing and pausing the video (one after another) fixes this.
The fix is applied if:
- we are not in picture in picture mode - here we do not have this problem
- we are not at the beginning of the video - here we also do not have this problem, plus if we apply it as we come back to the tab., it will change the "poster" of the video to the first frame of the video (which might be black)
=> 772 after resuming app ios video displayed black

Support/en.lproj/Localizable.strings, Views/Library/ZimFilesOpened.swift
Fixes: #809 
https://github.com/kiwix/kiwix-apple/assets/6784320/3e3aed36-c656-4fc2-b1d1-a6d242485035
=> Fix macOS unlink last ZIM file issue

Model/Entities/ZimFileMetaData/ZimFileMetaData.h, Model/Entities/ZimFileMetaData/ZimFileMetaData.mm, SwiftUI/Model/LibraryOperations.swift
=> Fix favIcons of opened ZIM files (not added via catalog download)

Model/Entities/Entities.swift, ViewModel/BrowserViewModel.swift, Views/Buttons/ShareButton.swift
=> Fix share/export content depending on it's type

Views/BuildingBlocks/WebView.swift
Fixes: #815 
Fixes: #816 
It also fixes some other scroll issues.
https://github.com/kiwix/kiwix-apple/assets/6784320/9a36f06c-5ce5-457c-b8d7-a72da21fbf4e
https://github.com/kiwix/kiwix-apple/assets/6784320/392015f2-3bf4-4113-b3bc-a00e059ce35d
=> Fix offset and animation issues

Support/injection.js
Fix javascript console log errors.
Depending on the content the ``messageHandlers.headingVisible`` might or might not be available.
=> Fix javascript console errors

ViewModel/BrowserViewModel.swift
Fixes: #817 
Currently this is how it looks with all the Water docs bookmarked on macOS:
=> Fix bookmarking of PDFs

App/SidebarViewController.swift, Views/BuildingBlocks/Favicon.swift
Fixes: #831 
Apart from fixing the warning issue (see #831),  the look and feel of the icons are improved, especially in Dark Mode.
=> Fix tab cell recycle, and favicon look for dark mode

Views/BuildingBlocks/WebView.swift
Fixes: #818 
After many experiments I haven't found anything useful, as the UI layer was crashing, and XCode could not debug it anymore...
So I investigated with earlier versions of the app, and after some git bisect it turned out that the commit 78b5f00 was the one to blame.
I still think it is not ideal, in terms of the code, but at the moment this is the very best version, that has no side effects.
I have tested it on all devices, and seems to work as expected.
=> Partial revert of 78b5f00, to fix webview black screen

App/App_iOS.swift, App/CompactViewController.swift, Model/Entities/Entities.swift, Model/Utilities/FileExporter.swift, SwiftUI/Patches.swift, ViewModel/BrowserViewModel.swift, Views/BrowserTab.swift, Views/Buttons/ExportButton.swift, Views/Buttons/PrintButton.swift, Views/Buttons/ShareButton.swift, Views/ViewModifiers/FileExportHandler.swift
Fixes: #814 
Renaming PDF specific parts to be more generic.
Figure out the file extension from the URL or from the mime-type of the content.
=> Fix file export extension and make it more generic

Model/Entities/Entities.swift, Support/de.lproj/Localizable.strings, Support/en.lproj/Localizable.strings, Support/fr.lproj/Localizable.strings, Support/ha.lproj/Localizable.strings, Support/he.lproj/Localizable.strings, Support/ia.lproj/Localizable.strings, Support/ig.lproj/Localizable.strings, Support/mk.lproj/Localizable.strings, Support/ru.lproj/Localizable.strings, Support/sl.lproj/Localizable.strings, Support/sv.lproj/Localizable.strings, Support/tr.lproj/Localizable.strings, Support/zh-hans.lproj/Localizable.strings, Support/zh-hant.lproj/Localizable.strings, SwiftUI/Model/DataModel.xcdatamodeld/DataModel.xcdatamodel/contents, SwiftUI/Model/ZimMigration.swift, ViewModel/BrowserViewModel.swift, Views/Bookmarks.swift, Views/BuildingBlocks/ArticleCell.swift
Here is the impact of removing the snippets and the image URL from the bookmarks.
The code is somewhat simpler. The HTML parser is still in use by the search results (I am not sure if that's needed btw), therefore that cannot be removed yet.
----------------------------------------
----------------------------------------
----------------------------------------
----------------------------------------
----------------------------------------
----------------------------------------
=> Remove Bookmark image and snippet

ViewModel/LibraryViewModel.swift
Fixes: #852 
The underlying parsing should be run only once at a time. If run from multiple threads at the same time it will crash as described in the issue.
Since we have 2 instances of the `LibraryViewModel` (one for the UI parts, one for background jobs - auto refresh), it was possible to crash in very rare cases, where the auto refresh kicked in the same time as a manual refresh. 
store the progress state in a single place, and secure it for multi-threaded access.
=> Fix Crash u_SetDictionary with LibraryViewModel multi-instance state

Model/Entities/ZimFileMetaData/ZimFileMetaData.h, Model/Entities/ZimFileMetaData/ZimFileMetaData.mm, Tests/CategoryFetchingTests.swift, Views/Library/ZimFilesCategories.swift
Fixes: #869
It turned out that the low-tech ZIM is available in multiple languages.
We do support multiple user languages, according to which we filter the content.
Matching these 2 lists were not fully working. Multiple user selected content languages could match a ZIM if it was on the list of user languages. It wasn't working the other way around. Eg. user has "fra" only selected, and the ZIM has multiple languages according to the feed: "eng,fra,deu,nld,spa,ita,por,pol,ara,vie,kor", the former selection could not find it.
With the updated query now we can create multi to multi matching queries, and the missing ZIM items will show up.
The remanning changes were needed to make things testable.
=> 869 no book found line for lowtech

App/CompactViewController.swift, Views/BrowserTab.swift, Views/BuildingBlocks/ContentSearchButton.swift
Fixes: #79 
The UI binding wasn't correct, as with the new tab a new WebView is created, and this feature was bound to the old instance, therefore the button remained disabled.
=> Fix Find in page availability

Views/Settings/Settings.swift
Fixes: #871 
Search snippet in settings is now a toggle instead of a drop down.
=> Change search snippet in setting to be a toggle

Views/ActivityViewController.swift
Fixes: #857 
I could not fully re-create this crash locally, the only thing that I have found was related to this additional presentation style. I have tested it on both iPhone and iPad and turns out we do not need it, as the View is already presented via SwiftUI `.sheet`.
=> Attempt to fix pop-over crash: remove extra modal style

App/App_iOS.swift, App/App_macOS.swift, App/SidebarViewController.swift, App/SplitViewController.swift, Model/DownloadService.swift, SwiftUI/Model/Database.swift, SwiftUI/Model/LibraryOperations.swift, SwiftUI/Model/ZimMigration.swift, Tests/CategoryFetchingTests.swift, Tests/LibraryRefreshViewModelTest.swift, ViewModel/BrowserViewModel.swift, ViewModel/LibraryViewModel.swift, ViewModel/NavigationViewModel.swift, ViewModel/SearchViewModel.swift, Views/Library/Library.swift, Views/Library/ZimFileDetail.swift, Views/Library/ZimFilesNew.swift, Views/Settings/LanguageSelector.swift
Fixes: #877
We had multiple background contexts from which the DB queries were operating, without much of synchronisation, but at the end they were forced to merge there changes into a single place.
Additionally to that, we had a token mechanism to synchronise these contexts, which was crashing from time to time.
Solution:
- Use Apple's built in merge context solution, which is easier in our scenario (the token based approach is more appropriate for App Extensions such as Lock Screen widgets and so on, which we do not have).
- Make sure we use a single background context the queries of which are also queued up properly, so there's less of a chance for conflicts.
Tested on macOS, iPad and iPhone. Both the download and the category fetching / parsing, and other DB related actions, such as …
=> Fix Crash with Single DB background context

Model/OPDSParser/OPDSParser.mm, Model/OPDSParser/OPDSParser.swift, Tests/OPDSParserTests.swift
Fixes: #874 
It turned out that if the data passed in is UTF8 compatible we won't have a crash, no matter how invalid the content of the data is (eg. not an xml format).
Whereas it was possible to crash the app with non uff-8 compatible input, like so:
Luckily we can handle this check on the swift / reader side.
Related unit tests were added, making sure we throw an error before the data with invalid encodings goes any deeper.
=> Make sure only utf8 compatible data can be passed into OPDS Parsing

SwiftUI/Model/SearchOperation/SearchOperation.swift
When searching Japanese Wikipedia, a summary of each search result is drawn in broken characters as shown in the image below.
This is probably due to the fact that encoding is not specified when converting HTML strings to `NSAttributedString`.
When this is corrected, the summary is correctly displayed as follows.
=> Fix search result list display of Japanese wikipedia

Model/Utilities/WebKitHandler.swift, ViewModel/BrowserViewModel.swift
Fixes: #895 
It turned out that it was a concurrency issue after all.
It was possible to execute a next step while we were receiving a "stop signal" from the Apple framework, due to the context switch to another thread, which also takes a fraction of time.
By adding `@MainActor` to the framework handle functions, it is now working as expected.
The additional thread safety could be simplified this way as well.
I leave it as a separate fix, for future reference (as it wasn't obvious at all), but I did tested this fix on both the main branch and on the range-request branch as well, and it works great.
=> WebKitHandler concurrency fix

project.yml
Before we do the release we need to align the version number to our updated milestone.
We can merge this after the weekly builds run, as the App Store version needs to be changed as well.
=> Change to release version 3.5.0

Model/DownloadService.swift, Views/BuildingBlocks/DownloadTaskCell.swift, Views/Library/ZimFileDetail.swift, Views/Library/ZimFilesDownloads.swift
Fix: #920
After my investigation it turned out that the real problem lied somewhere deeper.
My former fix in 7e706f32ad19fb353fb28209814c1bd07db7be94 did solved only part of the issue, and postponed the problem to the point where the download is finished.
We select a ZIMFile, for that we create a DownloadTask which keeps track of our progress, and can resume after app restart. So far so good.
The DownloadDetails view was relying on the DownloadTask itself, since that had a back reference to the ZIMFile, it could display all necessary details.
The problem is, that as it turns out SwiftUI has a bug, that if you delete the underlying managed object in our case the DownloadTask, which is deleted after the download completes, well... SwiftUI will just hold on to the old reference of that …
=> Fix crash: opening ZIM directly after download crashes the app on iPad

App/CompactViewController.swift, Views/BrowserTab.swift, Views/Welcome.swift
Fixes: #923 
We had 2 independent states, and 2 independent places on iPhone to open the `Library()`, which is a pop-up / sheet that presents the list of categories.
One could be triggered by the user, while the other could be triggered, when fetching the categories were completed.
Use a single state to indicate what sheet should be opened.
Additionally use a callback we can pass down, that is used to update this state, when the categories fetching is complete. Additionally only update the state, if there are no sheets presented.
=> Fix library double sheet, by using a common state

App/App_iOS.swift, App/App_macOS.swift, Support/Info.plist, Support/en.lproj/Localizable.strings, Support/qqq.lproj/Localizable.strings, SwiftUI/Model/LibraryOperations.swift, Tests/LibraryRefreshViewModelTest.swift, ViewModel/LibraryViewModel.swift, Views/Library/ZimFilesCategories.swift, Views/Library/ZimFilesNew.swift, Views/Settings/Settings.swift
Fixes: #922 
Summary of changes:
- remove background processing / background fetching for iOS
- since we no longer scheduling background task, those permissions were also removed
- auto update works in the following way: 
- If enabled we will check if the library should be re-fetched (meaning it's older than 1 day), in the following cases:
- the user foregrounds the app (either when starting the app, or background + foreground), on macOS it's the moment of the app starting
- the user visits either the "New" or "Categories" sections
- additionally we update the displayed messages while fetching, so instead of "No new ZIM Files" we indicate that we are still "Fetching..."
I've added some additional safeguard for the app start / foregrounding, as on Custom apps we do not need to fetch …
=> 922 my library is outdated 2 months old despite having checked to update automatically

Support/injection.js, ViewModel/BrowserViewModel.swift
Fixes: #916 
It seems it is an iOS 17 iPhone bug:
if we have a poster attribute set, the video starts with a black screen.
Currently in the "New" section:
- [TED collective (31 Jul 2024)](https://download.kiwix.org/zim/ted/ted_mul_collective_2024-07.zim.meta4)
- [TED humanities (02 Aug 2024)](https://download.kiwix.org/zim/ted/ted_mul_humanities_2024-08.zim.meta4)
TLDR: Remove poster attribute on iPhone iOS 17.
Looking deeper inside the HTML content we are using, we have the following structures:
```html
<div id="video-wrapper">
<div id="vjs_video_3"
data-setup="{&quot;techOrder&quot;: [&quot;html5&quot;, &quot;ogvjs&quot;], &quot;ogvjs&quot;: {&quot;base&quot;: &quot;assets/ogvjs&quot;}, &quot;autoplay&quot;: false, &quot;preload&quot;: true, &quot;controls&quot;: true, …
```
=> Fix iPhone video starting with a black screen on iOS 17 iPhone

Support/injection.js, Views/BuildingBlocks/WebView.swift
Fixes: #933 
Note it is based on the PR: https://github.com/kiwix/kiwix-apple/pull/924
As of [Apple's doc](https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/1614793-allowsinlinemediaplayback), we need to set:
``allowsinlinemediaplayback``
and additionally set:
``mediaTypesRequiringUserActionForPlayback`` - otherwise it's not working
and we need to enforce that there's a ``playsinline`` attribute on the html `<video>`.
=> 933 iphone video starts in full screen

Model/Entities/SearchResult.h, Model/Entities/SearchResult.m, SwiftUI/Model/SearchOperation/SearchOperation.swift, ViewModel/SearchViewModel.swift
Fixes: #940 
The issue was mainly that if we had the same url for the search result, but with different snippets, that created the same id for both, and one of them could not be rendered, because of this conflict.
It's safer to use the hash of full object, rather than the url's hash only, plus it's better to reduce the search results by the same id, before we process them any further.
I did simplify some of the loops around the search results processing, which made the search teeny-tiny faster.
Since we no longer do html parsing, the dispatchGroup solution is no longer needed, it just creates a lot of context switches between the threads, and it's actually measurably slower than without it.
=> Fix Blank item in search results

App/CompactViewController.swift, ViewModel/SearchViewModel.swift
Fixes: #946 
We store the button tab items when the search starts, and restore them when the search is cancelled. While the problem is that we should also restore them if the search succeeds, and we navigate away.
=> Fix search bar inconsistencies on iPhone

Support/br.lproj/Localizable.strings, Support/de.lproj/Localizable.strings, Support/en.lproj/Localizable.strings, Support/fi.lproj/Localizable.strings, Support/fr.lproj/Localizable.strings, Support/ha.lproj/Localizable.strings, Support/he.lproj/Localizable.strings, Support/hi.lproj/Localizable.strings, Support/ia.lproj/Localizable.strings, Support/ig.lproj/Localizable.strings, Support/ja.lproj/Localizable.strings, Support/ln.lproj/Localizable.strings, Support/mk.lproj/Localizable.strings, Support/pl.lproj/Localizable.strings, Support/ru.lproj/Localizable.strings, Support/skr-arab.lproj/Localizable.strings, Support/sl.lproj/Localizable.strings, Support/sv.lproj/Localizable.strings, Support/tr.lproj/Localizable.strings, Support/uk.lproj/Localizable.strings, Support/zh-hans.lproj/Localizable.strings, Support/zh-hant.lproj/Localizable.strings, Views/SearchResults.swift
Fixes: #954 
It seems to be an issue with SwiftUI itself, therefore the quickest fix we can do is not to have this confirmation dialog, but clearing the search history directly.
=> Remove search clear dialog, as it's crashing on iPadOS 17.5

Tests/LibraryRefreshViewModelTest.swift, ViewModel/LibraryViewModel.swift, Views/BuildingBlocks/Message.swift, Views/Library/ZimFilesCategories.swift, Views/Library/ZimFilesNew.swift, Views/Settings/Settings.swift, Views/Welcome.swift
Fixes: #959
Additional enum case for error, and re-use existing translation key for displaying the error.
=> Error handling for catalog not available 503

Views/BuildingBlocks/ArticleCell.swift
Fixes: #964
Replacement for the suggested PR: https://github.com/kiwix/kiwix-apple/pull/963
=> Fix snippets' color

Model/Migration/MigrationService.swift, Tests/MigrationServiceTests.swift
Initial generic migration service with tests.
Related to: #798 
We will yet to see in practice if `async` is needed for this, but for start let's keep it simple.
=> Migration services added

App/App_macOS.swift, CHANGELOG.md, ViewModel/BrowserViewModel.swift
Fixes: #962 
As mentioned in the ticket description, the easiest way to fix this issue is to disable the non-working window restore solution on macOS.
**Testing: Make sure you have only 1 version of Kiwix installed**. It is possible to have  multiple of them (eg from: AppStore, TestFlight, local build).
and as of [Apple docs](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app):
> If multiple apps register the same scheme, the app the system targets is undefined.
meaning that the clicked ZIM file might open in another version of Kiwix, if you have more than 1 installed.
=> Fix opening app with ZIM doesn't open ZIM

App/App_iOS.swift, App/App_macOS.swift, Model/Entities/SearchResult.m, Model/Migration/MigrateSchemeToZIM.swift, Model/Migration/MigrationService.swift, Model/Migration/Migrations.swift, Model/Utilities/URL.swift, Model/Utilities/WebKitHandler.swift, Support/Info.plist, Tests/BookmarkMigrationTests.swift, Tests/URLContentPathTests.swift, ViewModel/BrowserViewModel.swift, Views/BuildingBlocks/WebView.swift, Views/ViewModifiers/SaveContentHandler.swift
Fixes: #798 
**Note**: changes applied on top of the #956 PR.
Whenever we re-constructing urls (eg. to create bookmarks), the code has been updated.
This was the easy part, once the app starts we do a one-off migration, selecting the bookmarks that start with the url "kiwix://" and update those to be "zim://"
This was the hard part. We store the tabs together with the so called "interactiveState" of the webView loaded. Which is a serialised data provided by Apple. This contains the loaded url, and the browsing history (eg. former urls).
Formerly we used a "trick" to update such urls, for the [migration of ZIM files](https://github.com/kiwix/kiwix-apple/pull/700/files), which is in short utf8 decode the data, and from that regex replace the urls.
Now the same trick is not working to change …
=> 798 change url scheme from kiwix to zim

SwiftUI/Model/SearchOperation/SearchOperation.swift
If one of search results does not have a snippet, the following issues seem to occur:
- subsequent snippets are ignored
- results are not sorted.
This is caused by an early return from search function.
This PR tries to fix the issue.
=> Fix search results snippet and sorting issue

Views/BrowserTab.swift
Fixes: #978 
For some unknown reasons, SwiftUI is triggering the (formerly used) ``.onAppear`` callback even if the application is in the background.
Changing that to observing, when the application becomes ``active``, solves this issue.
I have tested it with the video in the ticket both on iPad 17, and macOS.
iPhone testing was omitted, as the changed file is not used there.
=> Fix video only on active scene

SwiftUI/Model/SearchOperation/SearchOperation.h, SwiftUI/Model/SearchOperation/SearchOperation.mm
Fixes: #980 
Superseeds #979
What we really want is unique search results, which is in fact unique URLs that the user can click on and navigate further. If 2 search results are linking to the same URL, that's a duplicate.
Store a set of ``foundURLs`` as we are processing the search results (both indexed and title search), and look for duplicates. Also make sure we adjust the URL endings to always contain the trailing "/" slash, but this is only for our comparison, the returned search result URLs should not be modified.
=> Remove duplicate search entries

Tests/OrderedCacheTests.swift, ViewModel/BrowserViewModel.swift, ViewModel/OrderedCache.swift, project.yml
Fixes: #988 
One of our dependencies is OrderedCollections, which is a large amount of extension from Apple, out of that we only use 1 file, and not even to it's full extent, as the most interesting part of it is used, when we run out of memory, and try to remove the "older" entries from the cache.
Proposition: instead of using a whole library, just do a simple class that does the same work.
=> Remove OrderedCollections dependency

README.md
The installation instruction listed the wrong installation command. I updated it to reflect the correct flag name, which is correctly listed in the kiwix-build repository, but for some reason was listed differently here.
=> corrected name of config flag

Views/BuildingBlocks/WebView.swift
Related to: #993 
On iPad 18.1 the following webView function is deprecated, and leads to a crash:
Whereas deleting the book does work on 18.1 (simulator):
https://github.com/user-attachments/assets/bdd5f1a3-c8c5-4604-b7d6-3c5104b73d3b
and it seems that unlinking the book also works on 18.1 (simulator):
https://github.com/user-attachments/assets/690a6112-e375-4880-97c8-5e0f1f8d75ac
Will test on device as well..
=> Avoid crash on iOS 18

App/App_macOS.swift, App/CompactViewController.swift, App/SplitViewController.swift, ViewModel/BrowserViewModel.swift, ViewModel/LaunchViewModel.swift, Views/BrowserTab.swift, Views/BuildingBlocks/LoadingView.swift, Views/LocalLibraryList.swift, Views/Welcome.swift, Views/WelcomeCatalog.swift
Fixes: #1006
There must be quite some changes to achieve this.
Custom apps (the ones without catalog / library capability) have a different loading
sequence compared to Kiwix app, since we do not have the "Fetching catalog" part.
Also the views were too tightly coupled with the loading states and library. Eg: Welcome screen was coupled with WebView.
I separated out the sequence of loading and its possible states into a new place, and wrapped that into a protocol with 1 implementation for Kiwix, and one for custom apps without Library.
I have re-tested both Kiwix and custom apps on iPhone iPad and macOS.
=> Improve launch sequence for custom apps

Brewfile, project.yml
=> Relies on libkiwix 14.0.0

ViewModel/BrowserViewModel.swift
=> Allow to load iFrame contents

.github/workflows/cd.yml, .github/workflows/ci.yml, README.md
Fixes: #971
I've updated the Readme file and the CD workflow to have our new approach documented and enforced.
=> 971 release tag seems wrong

SwiftUI/Model/DefaultKeys.swift, ViewModel/LibraryViewModel.swift
=> Use eTag for http caching

App/App_macOS.swift, Model/Payment.swift
Fixes: #1033 
In order to build this on CI, the certificate / provisioning profile needs to be changed.
=> Stripe Apple Pay for MacOS

App/App_macOS.swift, Model/Payment.swift
Removing the support button from custom apps, to make sure they do not appear there.
=> Remove support button from custom apps

App/App_macOS.swift
Fix opening the bookmark URLs for custom apps on macOS
=> Fix macOS opening bookmark URLs for custom apps

App/App_macOS.swift, SwiftUI/Model/Enum.swift, SwiftUI/Patches.swift, Views/ViewModifiers/FileImport.swift
=> Fix deeplink url opening on macOS

.github/workflows/cd.yml
Possible solution for FTP macOS CD builds.
Couldn't test it though, without merging and running the full release process.
=> Try not to use Apple Auth for FTP macOS builds

ViewModel/BrowserViewModel.swift
Fixes: #775 
It seems this line was lost in one of the git merges.
=> Fix open new tab via http blank link (lost line in merge)

ViewModel/LibraryViewModel.swift
Fixes: #1007 
As described in the re-opened issue, we need to handle the memory only stored categories to languages, when there's no new data coming from the http fetch (since it's 304, thanks to eTag).
=> Fix categories parsing, when eTag 304 is used

Model/CategoriesToLanguage.swift, Model/Defaulting.swift, SwiftUI/Model/Enum.swift, Tests/LibraryRefreshViewModelTest.swift, Tests/TestDefaults.swift, ViewModel/LibraryViewModel.swift, Views/Library/Library.swift, Views/Library/ZimFilesCategories.swift
Fixes: #1071
After double checking our build issues, I realised that some unit-test results, are heavily dependent on User Defaults, which is a key/value storage by Apple, which is persisted across sessions.
By running the same Unit-tests several times (repeatedly without building) some of them might fail.
- Wrap our user-default calls for those failing tests
- Use a test instance instead, that won't persist the results
- Also make sure that the created test db entries are cleaned-up properly
=> Fix "flaky" unit-tests

.github/actions/xcbuild/action.yml, .github/workflows/cd.yml, App/App_macOS.swift, Model/Brand.swift, project.yml
Fixes: #1055
Fix the CD process for macOS.
In short: the in-app-purchase is not supported by Developer ID signed apps (outside of the App Store), therefore we cannot use that capability in the FTP macOS build.
Although Apple Pay itself is supported, the In App Purchase capability that we use (for Donation - a purchase of a non-digital good) is not supported.
The found Apple reference: 
https://developer.apple.com/help/account/reference/supported-capabilities-macos
We need a follow up discussion, if we want to hide the support button in this case or maybe use a direct link instead (since this build is not going to be verified by Apple).
----- 
After the comments, the approach is that we inject the `HIDE_DONATION: true` key/value into the Support/Info.plist file for macOS FTP builds. For …
=> Remove support/donation for macOS FTP builds, as it's not supported outside of AppStore

CHANGELOG.md, project.yml
Update CHANGELOG and release number for 3.7.1.
=> Release 3.7.1 update CHANGELOG and release number

CHANGELOG.md, project.yml
Update app version and Changeling to 3.8.0
=> Update to 3.8.0

Views/Payment/CustomAmount.swift, Views/Payment/PaymentSummary.swift, project.yml
=> Fix localisation, remove debugPrint statement

Views/SearchResults.swift, Views/ViewModifiers/Focusable.swift, Views/ViewModifiers/KeyPressHandler.swift, Views/ViewModifiers/MoveCommand.swift
Fixes: #1083 
Based on the PR from: https://github.com/kiwix/kiwix-apple/pull/1079
FYA: [jarrodmoldrich](https://github.com/jarrodmoldrich)
https://github.com/user-attachments/assets/bf2e615d-2173-478b-a494-e0f253d52254
> [!NOTE] 
> The black keyboard is not part of the application, just meant to showcase which buttons were pressed, while navigating around.
=> Keyboard navigation improvements for macOS

.github/workflows/ci.yml
=> Remove in app payment for unit tests on macOS for CI

Views/Library/ZimFilesNew.swift
Fixes: #1093
Formerly if we switched to another application on macOS, or to another tab on iPhone (or iPad split screen), the search field preserved the typed in value, but the filter would no longer apply.
Similarly if the languages selected changed, the filter would not re-apply on macOS.
Use computed predicate for each view update, this way the filter properly re-applies.
https://github.com/user-attachments/assets/02009c75-a599-4b5a-8c30-944dd5d27332
https://github.com/user-attachments/assets/511511a2-8574-47b4-b79e-032b7647c6a9
=> Fix new ZIM files page search result updates

Views/BuildingBlocks/WebView.swift
Fixes: #1097 
Make sure we apply the `showBars` function depending on the screen size type, and not on the device, this solves the issue on iPad split screen.
=> Fix iPad split mode scroll to appear bottom bar

project.yml
It turns out we cannot register the former bundle ID, maybe it was used at some point,
so I am picking another one for our Widgets (Live Activity).
=> Update extension bundle ID

Views/Library/ZimFileDetail.swift
Fixes: #1112 
Tested on iPhone and iPad. MacOS is not affected by the change, as it's within the ``#if os(iOS)`` macro, plus we always display the unlink action on macOS.
https://github.com/user-attachments/assets/2fd3a435-a405-46fc-9940-0151588bd76e
https://github.com/user-attachments/assets/6e91ca41-afbb-48ff-a067-5ff84dc83f50
=> Fix refresh ZimFile details after download

Common/DownloadActivityAttributes.swift, Model/Utilities/DownloadTime.swift, Views/LiveActivity/ActivityService.swift, Widgets/Assets.xcassets/WidgetBackground.colorset/Contents.json, Widgets/DownloadsLiveActivity.swift, Widgets/Info.plist, Widgets/WidgetBackgroundModifier.swift
Fixes: #1107 
I have changed the background for the live-activity, so it matches the look and feel of other widgets on the Lock Screen. There's one issue though, Apple's environment property:
isActivityFullScreen has a bug, when we use min iOS is 16. According to their docs it has been "back-ported", but in reality using it is breaking the live-activity, and nothing will show up. Not using it is at the moment OK, I think, the only side effect is that in [iPhone standby mode](https://developer.apple.com/design/human-interface-guidelines/live-activities#StandBy) the live activity background is blurred instead of black. We can solve this only by updating to min iOS 17.
Long story short: local updates for "live" activities can get ignored by the system if we send them too often. From my tests …
=> 1107 improve live activities

Views/BuildingBlocks/ArticleActions.swift, Views/BuildingBlocks/CopyPasteMenu.swift, Views/Library/Library.swift, Views/Library/ZimFilesCategories.swift, Views/Library/ZimFilesDownloads.swift, Views/Library/ZimFilesNew.swift, Views/Library/ZimFilesOpened.swift
Mostly fixing the issue: #1116
There were 2 main issues:
- the [earlier search fix](https://github.com/kiwix/kiwix-apple/pull/1094), wasn't optimal in terms of scroll performance. 
- it turned out that SwiftUI gets lost, when we use `ViewModifier` within a `ForEach` loop. It was hard to track down, but the possible explanation for this, is that SwiftUI needs to see the view hierarchy tree in order to make performant diffs between states. Now it seems that the former `ViewModifier` was erasing too heavily the type of the underlying views, and the performance got worse. Solution is to use view composition instead of view modifier.
The good news is that it performs a lot better now. 
There needs to be a part 2 fix for this as well. There's a "micro hang" on a freshly installed app, when …
=> Fix library scroll issue - part 1

Views/BuildingBlocks/ArticleCell.swift, Views/BuildingBlocks/DownloadTaskCell.swift, Views/BuildingBlocks/ZimFileCell.swift, Views/Library/ZimFileDetail.swift, Views/Library/ZimFileDetailPreview.swift, Views/ViewModifiers/CellBackground.swift
As part of the fix for: #1116 
I am replacing one more viewModifier to make it the scroll even faster, and not inject the colorscheme (light or dark mode) into each cell we have (which is expensive).
Instead of that, we can use the built in system colours, which look better, I think.
I also updated the Download and the "Open Main Page" button colours for macOS, to make those more prominent, and making it more obvious for our users what the next step should be.
**TLDR: It will be faster and nicer.**
Tested on iPad and macOS.
=> Replace viewModifiers with inline, use system colours

.github/workflows/cd.yml, .github/workflows/ci.yml
As part of [this dependency update](https://github.com/kiwix/kiwix-apple/issues/1104), we need to update our CI CD to macOS 14 (and once this is merged to Xcode 16.2).
=> Update to macOS 14

.github/actions/xcbuild/action.yml
This reverts commit 01b8029a052de6fe8bee55aaab01cf2e32f36549, reversing changes made to 1deee2d19945fc1f57717dad8e669b75f515ec0e.
Xcode 16 is failing to build iOS at the moment:
https://github.com/kiwix/kiwix-apple/actions/runs/13473510711
Reverting to the last known working state.
=> Revert "Merge pull request #1121 from kiwix/xcode-16.2"

App/CompactViewController.swift, ViewModel/BrowserViewModel.swift, ViewModel/NavigationViewModel.swift, ViewModel/SearchViewModel.swift, Views/Bookmarks.swift, Views/BrowserTab.swift
Improvements for the issue: #1115
Part of my investigation on why the side menu is "sticky" sometimes.
In short when we leave or arrive at a specific menu item we do certain DB operations, which can take some small amount of time. Additionally setting up some models might take additional time (eg: SearchViewModel).
**Solution:** 
We can do those appear/disappear operations asynchronously, and it's enough to have 1 SearchViewModel across the lifetime of the app, this makes the UI more smooth.
=> 1104 side menu optimisation

App/CompactViewController.swift, Model/Defaulting.swift, SwiftUI/Model/DefaultKeys.swift, Tests/TestDefaults.swift, ViewModel/BrowserViewModel.swift, ViewModel/NavigationViewModel.swift, ViewModel/SearchViewModel.swift, Views/Bookmarks.swift, Views/BrowserTab.swift, project.yml
Fixes: #1104 
Tested on iPad, iPhone and macOS.
Updating not to the latest version, but the highest we can still run on Xcode 15.4
=> Update defaults dependency to 8.2

Common/DownloadActivityAttributes.swift, Model/DownloadService.swift, Model/Downloads/DownloadService.swift, Model/Downloads/DownloadState.swift, Model/Downloads/DownloadTasksPublisher.swift, ViewModel/BrowserViewModel.swift, Views/LiveActivity/ActivityService.swift, Widgets/DownloadsLiveActivity.swift, Widgets/KiwixLogo.swift
Fixes: #1107
-----
I replaced the progress indicator, with a linear bar that is updating constantly, so for our users it is more smooth. We do update the "real" progress every 10 seconds, which changes the amount of downloaded values displayed above the bar, and that updates the timer below the bar, and makes the bar either speed up or slow down.
I've also added a timestamp for each update, this helps the system decide which updates can be dropped if they do queue up, so once the system "unblocks" the live activity it can apply the latest update. 
I think, this is the best we can do considering the constraints that the iOS (especially above 18.0) puts on us.
The original `DownloadService` file became too long, so I split that up by classes and moved under a new folder.
=> Use progress bar with timer updates for live activities

App/App_iOS.swift, App/CompactViewController.swift, App/SplitViewController.swift, CHANGELOG.md, Common/DownloadActivityAttributes.swift, Model/Utilities/DownloadTime.swift, ViewModel/NavigationViewModel.swift, Views/Library/Library.swift, Views/LiveActivity/ActivityService.swift, Widgets/DownloadsLiveActivity.swift, project.yml
Compared to the former approach it is solving the following issues:
- we start with a quicker refresh time for the live activity: 2 seconds, whereas if the system locks down the refresh to 10 sec, we have our fallback mechanism, to update both the progress bar to the real value once we can, and keep showing an estimated progress on the bar itself, and in the countdown. The former misalignment in the calculation has been fixed.
- thanks to a deep link solution, tapping on the live activity on the Lock Screen, will take the user to the "Downloads" section of the Kiwix app, where further action can be taken, even if the app was "left" on another screen, before the device was locked.
Note: Further work is needed, to add a direct "pause" / "resume" button, that could control the downloads from …
=> Live activities

SwiftUI/Model/SearchOperation/SearchOperation.mm
Fixes: #1161 
The objective-c compiler was not helpful to detect this. On the other hand, the documentation states, that the now checked values can return null, so it's better to check for them, to be on the safe side.
=> Fix app crash, double check for nil values on URL construction for search results

Model/Utilities/Date+Extension.swift, ViewModel/BrowserViewModel.swift, Views/BuildingBlocks/WebView.swift
Things I have found on macOS and iPhone.
Both the date formatter and the web-view configuration object is slow to create and we only really need one of each.
The date formatter is mainly used in ``defaultResponseHeaders`` (video local streaming).
-------
And opening a new browser tab is also improved.
(The first time measured will be longer in both cases, as the configuration and the first browser setup will take more time).
```
TIMER:: BrowserViewModel.init() took: 0.2607688333373517
TIMER:: BrowserViewModel.init() took: 0.011252750060521066
TIMER:: BrowserViewModel.init() took: 0.011210291646420956
TIMER:: BrowserViewModel.init() took: 0.011013375013135374
```
```
TIMER:: BrowserViewModel.init() took: 0.1968754583504051
TIMER:: BrowserViewModel.init() took: 0.012397083337418735
TIMER:: …
```
=> Profile and improve performance

App/App_iOS.swift, project.yml
It can cause the issue described in: #1169
If the app is crashing / stopping at the background task registered for Live Activities deep-links.
=> Remove live activities for release

Support/Info.plist
Some remaining part to be removed after: https://github.com/kiwix/kiwix-apple/pull/1172
=> Remove live activity from Info.plist

App/App_iOS.swift, App/App_macOS.swift, App/SplitViewController.swift, Model/DeepLinkService.swift, SwiftUI/Model/Enum.swift, ViewModel/NavigationViewModel.swift, Views/ViewModifiers/FileImport.swift
Fixes: #1169 
The deep-link / opening the app via an external ZIM file is causing one type of navigation, creating a new tab.
When the application is starting, it is trying to find the latest opened tab.
If these 2 things collide in time we have the bug described in #1169. It affects iOS only, as on macOS via the deep-link the system opens a completely new window (which additionally has a different navigation context).
- Create a DeepLinkService isolated to the main thread (@MainActor)
- When opening a ZIM file, immediately register it via a unique ID on the DeepLinkService
- Opening the ZIM file goes through a couple of hoops (eg: twice the Notification Center etc.), so we pass down the same unique ID via that route
- Once the tab is open (the deep link handling ends) call the …
=> 1169 openzim navigate to recent tab race fix

Views/SearchResults.swift
Fixes: #1090
Adding the capability to move between the search bar and the search results with up/down arrow on macOS.
The ideal would be to do so in other search results as well, eg. on the news / categories or bookmarks section, however those are displaying the results in a grid, and so far finding the displayed items (left/right/up/down) is non trivial in SwiftUI, so will keep this change narrowed down to the ZIM file search results, which is a 1 column list.
The solution is based partially on the ideas presented here: https://github.com/kiwix/kiwix-apple/pull/1079/files
https://github.com/user-attachments/assets/8ba85bf1-d280-4044-b236-a07ed3de5bce
FYA: @jarrodmoldrich
=> macOS search navigation v2

Model/Entities/Entities.swift, ViewModel/BrowserViewModel.swift, Views/BuildingBlocks/WebView.swift, Views/Buttons/OutlineButton.swift
Fixes: #1170 
There were 2 issues: 
- the former optimisation broke the Outlines, since the single instance web configuration was setting up the javascript listener, from where we get the outline items via a callback.
- I removed the title from the outline drop down, since it is not clickable, it just makes unnecessary noise (and might do duplication as well)
- If the top level item is a single one, we are removing it, instead of the former solution of flattening the hierarchy:
https://github.com/user-attachments/assets/7c576e22-752b-4e56-b799-945524b5bc09
=> 1170 fix outlines and collapsibility

App/App_macOS.swift, SwiftUI/Model/Enum.swift, Views/ViewModifiers/FileImport.swift
Fixes: #1179 
It fixes both opening a deep-link in split screen mode, and also opening a ZIM file in split screen mode.
=> 1179 macos window split screen loading fix

App/SidebarViewController.swift
Relates to #1184
After investigating this, the current state is, that we should not have support button for custom apps:
https://github.com/kiwix/kiwix-apple/blob/39b1f9d56ef0c2c3bcd6e99b332170f5de509e31/Model/Payment.swift#L126
We do not have the support button in current PhET on macOS and on iPhone, so as of today it is showing up by pure incident on iPad.
It turned out that after the former perf. optimisation + moving the support button to be part of the side menu item, we were no longer calling the function that determines the payment button type, which also checks for things like: is apple pay supported on this device, is it a custom app, and so forth.
So this had to be fixed for the both Kiwix itself, and custom apps as well.
We can treat adding the support button, and "re-branding" …
=> Fix the donation/support button on iPad

App/CompactViewController.swift, Views/Commands.swift
Fixes: #1142
Apart from re-arranging, had to delegate open settings functionality down the UI layers, while the random functionality up (which is based on the amount of ZIM files loaded, no ZIM files => disabled).
Tested on iPhone.
=> 1142 Make random button more accessible

.github/workflows/ci.yml, Model/OPDSParser/OPDSParser.swift, Tests/LibraryRefreshViewModelTest.swift, Tests/OPDSParserTests.swift, UITests_iPad/LoadingUI_iPad_Test.swift, ViewModel/LibraryViewModel.swift, Views/Library/Library.swift, Views/Payment/PaymentForm.swift, Views/Payment/PaymentResultPopUp.swift
Fixes: #1212 
Attempting to stabilize CI unit / UI tests.
After several attempts on GitHub actions, and also on BrowserStack couldn't make the UI tests deterministic enough...
**Proposing to have the UI tests running locally**, where they are stable.
Also added a couple of fixes, that are making the Unit tests more stable on CI.
**I've run them 7 times in a row, and all of them are green:**
https://github.com/kiwix/kiwix-apple/actions/runs/15666712426
Fixes:
- delete the kiwix app before launching the unit tests on the booted simulator
- make sure that the unit tests and the UI tests are running on different simulators
- use valid bundle ids for our test targets
- test targets are limited to the appropriate devices (iPad, iPhone, mac)
- the unit tests around ODPS parser, making sure the …
=> 1212 stabilize CI tests, add tab selection UI test (local)

Views/Settings/Settings.swift
Related to: #1101 
Proposing to move the "Misc" section higher in the Settings on iOS, this way the Support Kiwix button is at least above "the fold":
It might not fully solve the problem, but should convert better.
=> Move support button in iOS settings above the fold

Model/Utilities/QRCode.swift, Views/Hotspot/HotspotDetails.swift, Views/Hotspot/HotspotZimFilesSelection.swift
After profiling the applications, it turned out that the QR code generator is slowing things down a bit.
We can move this process to ``async``, to unblock the UI thread,
and add a loading indicator that we can show in the meantime.
=> Generate Hotspot QR code async

.github/workflows/ci.yml
It seems that since I've changed the macOS CI unit test command arguments here:
https://github.com/kiwix/kiwix-apple/commit/1bc6248fe7e16dbc2b871cae85fcfb105d97b0d1
things got worse.
Re-adding the argument: ``CODE_SIGNING_ALLOWED=NO``
=> Revert changes on macOS CI tests

Model/Hotspot/Hotspot.swift, Views/Hotspot/HotspotAddress.swift, Views/Hotspot/HotspotDetails.swift, Views/Hotspot/HotspotExplanation.swift, Views/Hotspot/HotspotObservable.swift, Views/Hotspot/HotspotZimFilesSelection.swift
Refactoring, removing duplicates and unused properties.
Creating re-usable views for displaying the address and QR code.
Unifying the code that is responsible for the state of the hotspot, and separating out the ZIM file selection.
=> 170 hotspot clean up

Model/Hotspot/KiwixHotspot.mm
Fixes: #1270 
As you can see below, the trailing slash is also included:
=> Hotspot URL not to display port 80

Model/Hotspot/Hotspot.swift, Model/Hotspot/KiwixHotspot.h, Model/Hotspot/KiwixHotspot.mm, Model/ZimFileService/ZimFileService.h, Model/ZimFileService/ZimFileService.mm
Fixes: #1275 
It turned out that due to the "lazy" opening of the ZIM files, if it wasn't opened earlier, it would not show up on the Hotspot.
Fixed by using the right function, and documented the difference between the functions for the future.
Also made sure that even in the worst case of not being able to open any of the ZIM files, the Hotspot would not start at all.
=> 1275 fix zims not visible on hotspot

App/App_iOS.swift, Model/Hotspot/Hotspot.swift
Fixes: #1272 
Based on the PR: #1282 
It solves the 2nd issue, of restarting the Hotspot Server when the Kiwix iOS App becomes active again, if needed.
I did tested macOS as well in this regard, and the Kiwix Hotspot keeps running even if I lock the screen and turn off the screen (CMD + CTRL + Q) and ESC. Based on that, I don't think we need to do anything extra on macOS.
=> Restart Hotspot on application becoming active if needed

Views/Buttons/TabsManagerButton.swift
=> Fix tabs overlay for iOS 26

Model/Downloads/DownloadService.swift, Support/en.lproj/Localizable.strings, Support/qqq.lproj/Localizable.strings, SwiftUI/Model/Enum.swift, ViewModel/BrowserViewModel.swift, Views/ViewModifiers/AlertHandler.swift
Fixes: #1308 
We can now display more detailed errors in various points of the download process:
=> Add detailed download errors

Views/BrowserTab.swift
Fixes #1317 
It can be placed to the left, but it won't work for us, as search suggestions are not showing up in this case. Probably a SwiftUI bug.
not applicable: the search-bar is already in the middle of the screen in both landscape and portrait
=> Place searchfield to the left

Views/SearchResults.swift
Fixes: #1320 
This was a custom app specific issue. For Kiwix we always have the search side bar in a useful state, since we display the local ZIM files to include in the search.
After the changes it makes more sense now:
=> Fix empty search side panel for custom apps
